language: php
php:
  - '7.3'

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Define an environment variable
env:
  - SYMFONY_VERSION="3.4.*" DB=db_test

# Update composer
before_install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:m:m -n --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

jobs:
    include:
        - stage: test
          script: ./vendor/bin/phpunit
          fast_finish: true
        - stage: deploy
          if: branch = dev AND NOT type = "pull_request"
          install:
              - openssl aes-256-cbc -K $encrypted_473c1532d197_key -iv $encrypted_473c1532d197_iv -in ec2_bms.enc -out ec2_bms.pem -d
              - chmod 400 ./ec2_bms.pem
          script: ./deploy.sh dev ./ec2_bms.pem
        - stage: deploy
          if: (NOT branch = master) AND tag IS present
          install:
              - openssl aes-256-cbc -K $encrypted_473c1532d197_key -iv $encrypted_473c1532d197_iv -in ec2_bms.enc -out ec2_bms.pem -d
              - chmod 400 ./ec2_bms.pem
          script: ./deploy.sh ${TRAVIS_TAG} ./ec2_bms.pem
        - stage: deploy
          if: branch =~ /^release\/.*$/ AND NOT type = "pull_request"
          install:
              - openssl aes-256-cbc -K $encrypted_473c1532d197_key -iv $encrypted_473c1532d197_iv -in ec2_bms.enc -out ec2_bms.pem -d
              - chmod 400 ./ec2_bms.pem
          script: ./deploy.sh ${TRAVIS_BRANCH} ./ec2_bms.pem
        - stage: deploy
          if: branch = master AND NOT type = "pull_request" AND tag IS present AND tag =~ /^v.*$/
          install:
              - openssl aes-256-cbc -K $encrypted_473c1532d197_key -iv $encrypted_473c1532d197_iv -in ec2_bms.enc -out ec2_bms.pem -d
              - chmod 400 ./ec2_bms.pem
          script: ./deploy.sh master ./ec2_bms.pem
