voucher:
    resource: "@VoucherBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

app.swagger_ui:
    path: /swg/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

control_path:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/index.html.twig

rest:
    type: rest
    prefix: /api/{firewall}
    # prefix: /api
    resource: "routing_rest.yml"
    requirements:
        firewall: wsse
