services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    user.user_service:
        class: UserBundle\Utils\UserService
        arguments: ['%google_client%', '%humanitarian_secret%', '@doctrine.orm.entity_manager', '@validator', '@service_container', '@security.role_hierarchy']
        public: true

    UserBundle\Utils\UserService: '@user.user_service'


#######################################################################################
##                                       WSSE                                        ##
#######################################################################################

    wsse.security.authentication.provider:
        class: UserBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["@fos_user.user_provider.username", "%kernel.cache_dir%/security/nonces", "@logger"]
        public: false

    wsse.security.authentication.listener:
        class: UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@wsse.security.authentication.provider"]
        public: false
        tags:
            - { name: monolog.logger, channel: wsse }
