services:


#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    user.user_service:
        class: UserBundle\Utils\UserService
        arguments: ['%linked_in_secret%', '%google_client%', '%humanitarian_secret%', '@doctrine.orm.entity_manager', '@validator', '@service_container', '@security.encoder_factory']
        public: true


#######################################################################################
##                                       WSSE                                        ##
#######################################################################################

    wsse.security.authentication.provider:
        class: UserBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["@fos_user.user_provider.username", "%kernel.cache_dir%/security/nonces"]
        public: false

    wsse.security.authentication.listener:
        class: UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@wsse.security.authentication.provider"]
        public: false
        tags:
            - { name: monolog.logger, channel: wsse }
