services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DistributionBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    DistributionBundle\Extension\BeneficiaryGenderExtension:
        tags:
            - { name: twig.extension }

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    distribution.assistance_service:
        class: DistributionBundle\Utils\AssistanceService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@serializer'
            - '@validator'
            - '@location_service'
            - '@distribution.commodity_service'
            - '@distribution.configuration_loader'
            - '@distribution.criteria_assistance_service'
            - '@transformer.selection_criterion_field'
            - '%distribution.retriever%'
            - '@service_container'
            - '@workflow.registry'

    distribution.assistance_beneficiary_service:
        class: DistributionBundle\Utils\AssistanceBeneficiaryService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@serializer'
            - '@validator'
            - '@service_container'
            - '@workflow.registry'

    distribution.criteria_assistance_service:
        class: DistributionBundle\Utils\CriteriaAssistanceService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@distribution.configuration_loader'
            - '@beneficiary.vulnerability_resolver'
            - '@serializer'

    distribution.configuration_loader:
        class: DistributionBundle\Utils\ConfigurationLoader
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%distribution.criteria%'

    distribution.modality_service:
        class: DistributionBundle\Utils\ModalityService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    distribution.commodity_service:
        class: DistributionBundle\Utils\CommodityService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    DistributionBundle\Mapper\AssistanceBeneficiaryMapper:
        arguments:
            - "@VoucherBundle\\Mapper\\BookletMapper"
            - "@DistributionBundle\\Mapper\\GeneralReliefItemMapper"
            - "@TransactionBundle\\Mapper\\TransactionMapper"
            - "@BeneficiaryBundle\\Mapper\\BeneficiaryMapper"
        public: true

    DistributionBundle\Mapper\AssistanceCommunityMapper:
        arguments:
            - "@VoucherBundle\\Mapper\\BookletMapper"
            - "@DistributionBundle\\Mapper\\GeneralReliefItemMapper"
            - "@TransactionBundle\\Mapper\\TransactionMapper"
            - "@BeneficiaryBundle\\Mapper\\CommunityMapper"
        public: true

    DistributionBundle\Mapper\AssistanceInstitutionMapper:
        arguments:
            - "@VoucherBundle\\Mapper\\BookletMapper"
            - "@DistributionBundle\\Mapper\\GeneralReliefItemMapper"
            - "@TransactionBundle\\Mapper\\TransactionMapper"
            - "@BeneficiaryBundle\\Mapper\\InstitutionMapper"
        public: true

    DistributionBundle\Mapper\CampMapper:
        public: true

    DistributionBundle\Mapper\GeneralReliefItemMapper:
        arguments:
            - "@serializer"
        public: true

    DistributionBundle\Repository\AssistanceBeneficiaryRepository:
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - DistributionBundle\Entity\AssistanceBeneficiary

    assistance.repository:
        class: DistributionBundle\Repository\AssistanceRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - DistributionBundle\Entity\Assistance
        public: true

#######################################################################################
##                                       CSV                                         ##
#######################################################################################

    distribution.distribution_csv_service:
        class: DistributionBundle\Utils\DistributionCSVService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@beneficiary.household_export_csv_service'
            - '@service_container'
            - '@beneficiary.household_service'
            - '@serializer'
            - '@validator'
            - "@request_validator"
            - "@beneficiary.csv_to_array_mapper"

    distribution.export_legacy.smartcard_invoice:
        class: DistributionBundle\Export\SmartcardInvoiceLegacyExport
        arguments:
            - '@translator'
            - '@CommonBundle\Mapper\LocationMapper'
        public: true

    distribution.export.smartcard_invoice:
        class: DistributionBundle\Export\SmartcardInvoiceExport
        arguments:
            - '@translator'
            - '@CommonBundle\Mapper\LocationMapper'
            - '@smartcard_purchase.repository'
        public: true
